server:
  port: 8008
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://cloud-user
          predicates:
            - Path=/cloud-user/**
        - id: auth-service
          uri: lb://cloud-auth
          predicates:
            - Path=/cloud-auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
jwt:
  skipAuthUrls: /cloud-regist,/cloud-admin